Repository arctern-io/arctern-docs, pull requests merged in 2020-05, with the labels that each got.

#70 branch 0.1.x render doc check
  doc-cn/source/python/api/render/function/layer/weighted_pointmap.md
  doc-cn/source/spark/api/render/function/layer/choroplethmap.md
  doc-cn/source/spark/api/render/function/layer/heatmap.md
  doc-cn/source/spark/api/render/function/layer/iconviz.md
  doc-cn/source/spark/api/render/function/layer/pointmap.md
  doc-cn/source/spark/api/render/function/layer/weighted_pointmap.md
Labels: arctern-0.1.0

#92 Fix data source import bugs.
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Centroid.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Centroid.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_CurveToLine.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_CurveToLine.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_HausdorffDistance.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_HausdorffDistance.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_Centroid.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_Centroid.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_CurveToLine.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_CurveToLine.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_HausdorffDistance.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_HausdorffDistance.po
  doc-cn/source/python/data_source/file_data.md
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/file_data.md
  doc-cn/source/spark/data_source/geometry_data_format.md
Labels: arctern-0.1.1

#99 fix typos
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#100 fix typos
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#110 Add python script to update po file.
  doc-cn/create_html.py
  doc-cn/update_po.py
Labels: arctern-0.1.1

#113 Add python script to update po file.
  doc-cn/create_html.py
  doc-cn/update_po.py
Labels: arctern-0.1.1

#121 fix spark quick start
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.1

#120 fix quick start spark
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.1

#122 Check pandas quick start and add verison check
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#125 Check pandas quick start and add verison check
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#129 Minor revision on offline spark installation
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#128 Minor revision on offline spark installation
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#131 change python to Python
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
Labels: arctern-0.1.1

#136 Update installation and correct some words
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/command.md
  doc-cn/source/restful/api/function/create_scope.md
  doc-cn/source/restful/api/function/delete_scope.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/loadfile.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/query.md
  doc-cn/source/restful/api/function/savefile.md
  doc-cn/source/restful/api/function/table_schema.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
  doc-cn/source/restful/restful_quick_start.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/installation_and_deployment/deploy-with-docker-compose-cn.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.1

#146 Editorial updates to Branch 0.1.x
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/restful/restful_quick_start.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.1

#148 Format changes
  doc-cn/source/python/data_source/file_data.md
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/file_data.md
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/jdbc_data.md
Labels: arctern-0.1.1

#152 Fix install online and quick-start of pandas and spark
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
  scripts/pandas_quick_start.py
Labels: arctern-0.1.0

#151 fix some detail issue of restful doc
  doc-cn/source/restful/restful_quick_start.md
  doc-cn/source/restful/webserver_installation_config.md
  scripts/quickstart/restful/restful_quick_start.py
Labels: arctern-0.1.1, documentation

#149 fix some detail issue of restful doc
  doc-cn/source/restful/restful_quick_start.md
  doc-cn/source/restful/webserver_installation_config.md
  scripts/quickstart/restful/restful_quick_start.py
Labels: arctern-0.1.1, documentation

#156 add spark_quick_start.py and pandas_quick_start.py
  scripts/quickstart/python/pandas_quick_start.py
  scripts/quickstart/spark/spark_quick_start.py
Labels: arctern-0.1.1

#155 add spark_quick_start.py
  scripts/quickstart/python/pandas_quick_start.py
  scripts/quickstart/spark/spark_quick_start.py
Labels: arctern-0.1.1

#157 Update code format
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/aggr/ST_Envelope_Aggr.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Envelope.po
  doc-cn/source/python/data_source/file_data.md
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/python/quick_start/quick_start.rst
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/command.md
  doc-cn/source/restful/api/function/create_scope.md
  doc-cn/source/restful/api/function/delete_scope.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/loadfile.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/query.md
  doc-cn/source/restful/api/function/savefile.md
  doc-cn/source/restful/api/function/table_schema.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
  doc-cn/source/restful/restful_quick_start.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/data_source/file_data.md
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/jdbc_data.md
  doc-cn/source/spark/installation_and_deployment/deploy-with-docker-compose-cn.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
  doc-en/source/spark/installation_and_deployment/deploy-with-docker-compose.md
  doc-en/source/spark/installation_and_deployment/install_arctern_on_spark_en.md
  doc-en/source/spark/installation_and_deployment/offline_install_arctern_on_spark_en.md
  doc-en/source/spark/installation_and_deployment/set-up-a-local-channel-for-installing-arctern.md
Labels: arctern-0.1.1

#160 Fix code display bugs
  doc-cn/source/index.rst
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Envelope.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/aggr/Spark_ST_Envelope_Aggr.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_Envelope.po
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/python/python.rst
  doc-cn/source/restful/restful.rst
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
  doc-cn/source/spark/spark.rst
  scripts/quickstart/spark/spark_quick_start.py
Labels: arctern-0.1.1

#159 Fix code display bugs
  doc-cn/source/index.rst
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/aggr/ST_Envelope_Aggr.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Envelope.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/python/api/geospatial/function/geospatial/ST_Envelope.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/aggr/Spark_ST_Union_Aggr.po
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_Envelope.mo
  doc-cn/source/locale/zh_CN/LC_MESSAGES/spark/api/geospatial/function/geospatial/Spark_ST_Envelope.po
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/python/python.rst
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
  doc-cn/source/spark/spark.rst
  scripts/quickstart/spark/spark_quick_start.py
Labels: arctern-0.1.1

#161 Update restful quick start.
  doc-cn/source/restful/api/api.rst
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/command.md
  doc-cn/source/restful/api/function/create_scope.md
  doc-cn/source/restful/api/function/delete_scope.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/loadfile.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/query.md
  doc-cn/source/restful/api/function/savefile.md
  doc-cn/source/restful/api/function/table_schema.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
  doc-cn/source/restful/restful_quick_start.md
Labels: arctern-0.1.1

#162 improve restful api
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
Labels: arctern-0.1.2

#163 update webserver_installation_config.md
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#164 Fix restful quick start
  doc-cn/source/restful/restful_quick_start.md
Labels: arctern-0.1.2

#165 Update RESTful quick start
  doc-cn/source/restful/restful_quick_start.md
Labels: arctern-0.1.2

#167 Add restful quick start.
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
Labels: arctern-0.1.2

#166 fix errors in RESTful api
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/command.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/savefile.md
  doc-cn/source/restful/api/function/table_schema.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
Labels: arctern-0.1.2

#169 Update RESTful installation
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#170 Config copy code
  doc-cn/create_html.py
Labels: arctern-0.1.2

#171 Config copy code
  doc-cn/create_html.py
Labels: arctern-0.1.2

#168 add arctern channel
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#172 Update Pandas docs
  doc-cn/source/python/data_source/file_data.md
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.2

#174 Adjust installation doc for restful
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#175 Delete jdk8 dependency for python install.
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
Labels: arctern-0.1.2

#176 Fix error in restful docs
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  img/icon/arctern-logo.png
  img/restful-result/choroplethmap.png
  img/restful-result/choroplethmap_spark.png
  img/restful-result/fishnetmap.png
  img/restful-result/fishnetmap_spark.png
  img/restful-result/heatmap.png
  img/restful-result/heatmap_spark.png
  img/restful-result/icon_viz.png
  img/restful-result/icon_viz_spark.png
  img/restful-result/pointmap.png
  img/restful-result/pointmap_spark.png
  img/restful-result/weighted_pointmap.png
  img/restful-result/weighted_pointmap_spark.png
Labels: arctern-0.1.2

#177 Update restful docs.
  doc-cn/source/restful/api/api.rst
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  doc-cn/source/spark/installation_and_deployment/installation_and_deployment.rst
  doc-en/source/spark/installation_and_deployment/installation_and_deployment.rst
Labels: arctern-0.1.2

#178 Add restful config
  doc-cn/source/restful/restful_config.md
Labels: arctern-0.1.2

#179 Update restful docs
  doc-cn/source/restful/restful_config.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#183 Update code comments
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#184 add restful server proxy faq
  doc-cn/source/restful/webserver_installation_config.md
Labels: arctern-0.1.2

#182 Update docs.
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
Labels: arctern-0.1.2

#186 Update spark docs
  doc-cn/source/python/data_source/geometry_data_format.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/restful/restful_config.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/jdbc_data.md
  doc-cn/source/spark/installation_and_deployment/deploy-with-docker-compose-cn.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.2

#189 Snyc pandas and spark docs
  doc-cn/source/python/installation_and_deployment/install_arctern_on_python.md
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/spark/data_source/file_data.md
  doc-cn/source/spark/data_source/geometry_data_format.md
  doc-cn/source/spark/data_source/jdbc_data.md
Labels: arctern-0.1.2

#188 Editorial changes
  doc-cn/source/python/quick_start/quick-start-pandas.md
  doc-cn/source/restful/restful_config.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/spark/data_source/file_data.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
  doc-cn/source/spark/quick_start/quick-start-spark.md
Labels: arctern-0.1.2

#190 Add docs
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/webserver_installation_with_docker.md
  doc-cn/source/spark/installation_and_deployment/install_arctern_on_spark_cn.md
Labels: arctern-0.1.2

#191 update fishnet example for docker
  doc-cn/source/restful/webserver_installation_with_docker.md
  img/restful-result/fishnetmap_docker.png
Labels: arctern-0.1.2, documentation, enhancement

#192 fix docker-compose command
  doc-cn/source/restful/webserver_installation_with_docker.md
Labels: arctern-0.1.2, bug, documentation

#193 Update docker doc
  doc-cn/source/restful/webserver_installation_with_docker.md
  doc-cn/source/spark/installation_and_deployment/offline_install_arctern_on_spark_cn.md
Labels: arctern-0.1.2

#194 change file url
  doc-cn/source/restful/webserver_installation_with_docker.md
Labels: arctern-0.1.2, bug
