Repository arctern-io/arctern-docs, pull requests merged in 2020-07, with the labels that each got.

#42 Fix github action bug
  docker/arctern-conda-dep.yml
  docker/docker-entrypoint.sh
  version.json
Labels: bug, enhancement

#43 add doctest support.
  doc-en/source/conf.py
  docker/docker-entrypoint.sh
Labels: enhancement

#44 Fix bug to 0.3.x
  docker/arctern-conda-dep.yml
  docker/docker-entrypoint.sh
  version.json
Labels: bug

#45 Add doctest
  docker/docker-entrypoint.sh
  version.json
Labels: enhancement

#50 github action for arctern-io doctest
  .github/workflows/doc.yml
  .gitignore
  doc-en/source/api_reference/api_reference.rst
  doc-en/source/api_reference/cluster_api/cluster_api.rst
  docker/Dockerfile
  docker/arctern-conda-dep.yml
  docker/docker-entrypoint.sh
Labels: documentation

#48 Add RESTful docs
  doc-cn/source/index.rst
  doc-cn/source/resftful/webserver_installation_config.md
  doc-cn/source/restful/api/api.rst
  doc-cn/source/restful/api/function/choroplethmap.md
  doc-cn/source/restful/api/function/command.md
  doc-cn/source/restful/api/function/fishnetmap.md
  doc-cn/source/restful/api/function/heatmap.md
  doc-cn/source/restful/api/function/icon_viz.md
  doc-cn/source/restful/api/function/loadfile.md
  doc-cn/source/restful/api/function/pointmap.md
  doc-cn/source/restful/api/function/query.md
  doc-cn/source/restful/api/function/savefile.md
  doc-cn/source/restful/api/function/table_schema.md
  doc-cn/source/restful/api/function/weighted_pointmap.md
  doc-cn/source/restful/install_arctern_on_spark_cn.md
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/restful_config.md
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
  doc-cn/source/restful/webserver_installation_config.md
Labels: documentation

#53 add cluster installation document and restructure installation docs
  doc-cn/source/cluster/cluster.rst
  doc-cn/source/cluster/cluster_code.md
  doc-cn/source/index.rst
  doc-cn/source/install/cluster_installation.md
  doc-cn/source/install/img/check_cluster.png
  doc-cn/source/install/install_arctern_on_spark_cn.md
  doc-cn/source/install/standalone_installation.md
  doc-cn/source/install/webserver_installation_config.md
  doc-cn/source/quick_start/demo.md
  doc-cn/source/quick_start/quick_start.rst
  doc-cn/source/restful/install_arctern_on_spark_cn.md
  doc-cn/source/restful/restful.rst
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
Labels: enhancement

#54 add png url and fix bug
  doc-cn/source/api_reference/api_reference.rst
  doc-cn/source/api_reference/cluster_api/cluster_api.rst
  doc-cn/source/cluster/cluster_code.md
  doc-cn/source/install/install_arctern_on_spark_cn.md
  doc-cn/source/install/webserver_installation_config.md
  doc-cn/source/restful/img/heatmap.png
  doc-cn/source/restful/img/heatmap_spark.png
  doc-cn/source/restful/restful_quick_start_on_python.md
  doc-cn/source/restful/restful_quick_start_on_spark.md
Labels: bug

#56 add step of configuring hive-site.xml
  doc-cn/source/install/install_arctern_on_spark_cn.md
Labels: enhancement

#57 add missing url
  doc-cn/source/restful/api/function/loadfile.md
  doc-cn/source/restful/file_data.md
Labels: bug

#58 Added api
  doc-cn/source/api_reference/api_reference.rst
  doc-cn/source/api_reference/plot/plot.rst
  doc-cn/source/api_reference/standalone_api/geodataframe.rst
  doc-cn/source/api_reference/top_level_functions/top_level_functions.rst
Labels: documentation

#60 specify .bashrc location clearly and delete uncessary cmds.
  doc-cn/source/install/install_arctern_on_spark_cn.md
  doc-cn/source/install/standalone_installation.md
  doc-en/source/quick_start/standalone_installation.md
Labels: bug

#62 Update GeoSeries api rst file
  doc-cn/source/api_reference/plot/plot.rst
  doc-cn/source/api_reference/standalone_api/geoseries.rst
  doc-en/source/api_reference/plot/plot.rst
  doc-en/source/api_reference/standalone_api/geoseries.rst
Labels: documentation

#70 EN translation of files under doc-en/source/restful.
  doc-cn/source/restful/restful_config.md
  doc-en/source/restful/api/function/choroplethmap.md
  doc-en/source/restful/api/function/command.md
  doc-en/source/restful/api/function/fishnetmap.md
  doc-en/source/restful/api/function/heatmap.md
  doc-en/source/restful/api/function/icon_viz.md
  doc-en/source/restful/api/function/loadfile.md
  doc-en/source/restful/api/function/pointmap.md
  doc-en/source/restful/api/function/query.md
  doc-en/source/restful/api/function/savefile.md
  doc-en/source/restful/api/function/table_schema.md
  doc-en/source/restful/api/function/weighted_pointmap.md
  doc-en/source/restful/file_data.md
  doc-en/source/restful/restful_config.md
  doc-en/source/restful/restful_quick_start_on_python.md
  doc-en/source/restful/restful_quick_start_on_spark.md
Labels: documentation

#71 Updated version.js to release.
  version.json
Labels: documentation
